### ISSUE TITLE
Negative Minting After Wallet Update

### ISSUE THREAD

**Issue by c4f3b4b3** [CryptoCoderz/Espers#13] opened 2017-10-26 21:52 UTC
Status: 87 confirmations, broadcast through 15 nodes
Date: 10/26/2017 07:58
Source: Generated
Debit: 0.00 ESP
Net amount: -1451441.92 ESP
Transaction ID: c62b2bbc95b841d1270dde200e778276c1c8ce5f2ed896a48fd9d5f26715e0a2-000

**Comment by ctgiant** [comment] 2017-10-27 13:35
That is how it should be. It shows a negative net amount until it reaches maturity (90 confirmations).  Once the transaction is mature the net amount in this detailed view should equal the number staked in the right column of the transactions list (not the detailed view).

It does this because that is the number of coins that the stake was against, which means that they are the ones that generated the stake and are going to be immature once the transaction is confirmed.

**Comment by CryptoCoderz** [comment] 2018-01-26 08:39
ctgiant has explained this, thank you.

Closing issue

**Closed as completed by CryptoCoderz** 2018-01-26 08:39 UTC
