### ISSUE TITLE
Latest release compile issues

### ISSUE THREAD

**Issue by pinpins** [CryptoCoderz/Espers#42] opened 2020-06-01 06:48 UTC
Hello,

Ubuntu 16.04 does not compile below error occurs

```
                                                                                                                 ^
core/main.cpp:140:109: error: ‘boost::placeholders’ has not been declared
     g_signals.EraseTransaction.disconnect(boost::bind(&CWalletInterface::EraseFromWallet, pwalletIn, boost::placeholders::_1));

```

**Comment by CryptoCoderz** [comment] 2020-06-03 05:33
Hello,

"This is by design; from now on, #include <boost/bind/bind.hpp> defines _1 in namespace boost::placeholders without importing it into the global namespace, to avoid conflicts. For backward compatibility, #include <boost/bind.hpp> includes boost/bind/bind.hpp and does using namespace boost::placeholders;.

So, to make the code compile, either include boost/bind.hpp instead, or add using namespace boost::placeholders;."

Sourced from: https://svn.boost.org/trac10/ticket/11902

I will be correcting this asap just wanted to provide you with some info on this issue.
---------------------------------------------------------------------------------------------

Another solution is using "boost::arg<1>()" as apposed to "boost::placeholders::_1"

**Comment by pinpins** [comment] 2020-06-04 06:09
ok, just let me know once this is committed to master, I will pull latest

**Comment by CryptoCoderz** [comment] 2020-06-04 06:32
Absolutely will do, Please give me a couple hours and it should be posted.

I was exploring the different methods and what would be a best practices solution for all platforms

**Comment by CryptoCoderz** [comment] 2020-08-21 01:27
@pinpins please try compiling once again, I have pushed a commit that should solve the issues you were experiencing.

resolved in: https://github.com/CryptoCoderz/Espers/commit/7d8554a2ddd767b3999c0acad06f1babe9678161

**Closed as completed** 2020-08-21 01:27 UTC
