### ISSUE TITLE
Windows wallet 0.8.6.9: switching views fails sometimes

### ISSUE THREAD

**Issue by cryptonoob42** [CryptoCoderz/Espers#14] opened 2017-10-28 15:40 UTC
In the Windows wallet, v 0.8.6.9, there seems to be a problem switching views. Steps to reproduce on my machine:

1. Start the wallet. The dashboard / overview appears.
2. Click on "Receive", the receive view appears.
3. Click on "Dashboard", the dashboard appears.
4. Click on "Generate ESP", nothing changes. The dashboard view remains visible.
5. Click on "Messaging", the "COMING SOON" message is displayed.
6. Click on "Generate ESP", nothing changes. The "COMING SOON" message remains visible.

It seems like either the "Generate ESP" view was removed but the button was left in the menu, or switching to this view is somehow broken in a different manner.

**Comment by bitcoinx2** [comment] 2017-10-28 16:06
Confirmed on Debian GNU/Linux, 32 bit. This problem has existed since the new wallet design (with the statistics being included in the overview tab) was introduced.

**Comment by cryptonoob42** [comment] 2017-10-28 16:24
The generate view implementation was removed with commit https://github.com/CryptoCoderz/Espers/commit/24405fed297a065d5c03c5734a7d35759050067d but it seems like it's still listed in the menu on the left nonetheless. Should be easy to fix. I'll take a look at it just for fun and if I get it fixed, I'll create a PR :)

**Comment by cryptonoob42** [comment] 2017-10-28 17:26
I've tested this change on Linux Mint 18.2, 64 bit. Cannot test on Windows unfortunately.

**Comment by GithubEspers** [comment] 2017-11-08 13:16
Cryptonoob42, is this an issue that you can assist me with? I am in dire need of assistance and I haven't heard from the developers for Espers. If you can, I truly appreciate it. Please see below issue that I am facing and I don't know what else to do to save my investment that I was hoping to keep in the new wallet.

****

**Comment by GithubEspers** [comment] 2017-11-08 13:17
Hi - I had my Espers coins in Nova Exchange which I transferred yesterday (11/02/17) to my updated wallet on my Mac computer. Since yesterday I still haven’t seen the deposit to my wallet and I am getting very frustrated. I posted messages on twitter seeking help but so far I am still waiting. Can you please assist me with this issue? I communicates with Nova Exchange and they directed back to Espers because this seems to be a wallet issue. The funds have cleared successfully from Nova Exchange.


Transaction ID: | 9ec98a02ee62cfb9dffa40c8bbe0c552c76ad30989890380532cfe4ffa266239
-- | --


Transaction ID: | 97064bee0192f56b3b0df381831ed16548f198a0eab35a277f2ad2bb4e223b44
-- | --

Please advise at your earliest convenience because Nova Exchange will be closing and I don't want to lose my investments.

I am using the latest wallet and running MacOS Sierra Version 10.12.6

Best regards,

Michael

**Comment by cryptonoob42** [comment] 2017-11-11 12:02
Hi @GithubEspers , I'm not a member of the Espers team, I just reported an issue and provided a bugfix :) I see that you have opened a new issue where you describe the problem, which is good. Maybe you should ask in the Espers [Discord](https://discord.gg/JpBbujR) where many people hang out and someone can probably help you. Good luck!

**Comment by CryptoCoderz** [comment] 2018-01-26 08:35
Hello folks,

I personally apologize for not getting back to you sooner about this.

The reasoning behind the "dead" tab that leads to no where is that it is to be re-enabled as the built in mining was finished over the winter finally (which is some of the many things we were working on) so it was felt that there was no need to pull the tab though I can see how this can both cause concern and be quite annoying as the tab does not lead anywhere

Bear in mind this tab will work again and actually provide some useful functionality in the future

**Closed as completed by CryptoCoderz** 2018-01-26 08:35 UTC
