### ISSUE TITLE
Error on blockchain-sync 'ORPHAN BLOCK 751' at blockcount 705221

### ISSUE THREAD

**Issue by typoworx-de** [CryptoCoderz/Espers#18] opened 2018-01-24 19:14 UTC
I'm getting error on blockchain-sync 'ORPHAN BLOCK 751' at blockcount 705221.

debug.log tail contains:
```
ProcessBlock: ORPHAN BLOCK 751, prev=000000000113c6818b2e1a462a0123daa5ba1f4ed414167685080220de0f1087
ProcessBlock: ORPHAN BLOCK 751, prev=0000052019af0156d700e2e1ff5a8b443f64b9fa33b3ef2ad4d2b17026610a9f
ProcessBlock: ORPHAN BLOCK 751, prev=00000fa910fc42ce05abf9ca56ead79c16375562afdf6c0e8c1e8f6014b32796
ProcessBlock: ORPHAN BLOCK 751, prev=5f75c23880e2ed64bedcbff40a75f83522537274513417b33084aee46a2f27b7
ProcessBlock: ORPHAN BLOCK 751, prev=0000045625c1d977c708f21f00d44119fa5c4bd993a205bafed02aee22cf4fe6
ProcessBlock: ORPHAN BLOCK 751, prev=00000eeaf26a5c69bcbba9c3d4b181b6e8f851e105ed12e2e7b516a874d012d0
ProcessBlock: ORPHAN BLOCK 751, prev=00000c0f2ee69b8342b64b8a9af56199f0730de4a4c38de9bffe49b1293fbb15
ProcessBlock: ORPHAN BLOCK 751, prev=00000c45d02cd530fcc0aaf42f0f9d91d553814f9b5d00755603c3bbf15aee3e
ProcessBlock: ORPHAN BLOCK 751, prev=0000074fbf31707b1823e77dae23167210d1afb9aeedb2748a59f0ce98e7780e
ProcessBlock: ORPHAN BLOCK 751, prev=00000c9f10e22321a32af7c193581bd3738e6692eed9311eb20ee17284620c7d
```
I already tried to delete whole blockchain-data and resynced from zero. But error appears again.

How can this be fixed? Is there some re-index or rollback that is able to fix this?

**Comment by typoworx-de** [comment] 2018-01-24 19:23
As statet here openssl >= 1.0 (heartbleed fix) may be the culprit? OpenSSL 0.9.3 is said to be working.
https://github.com/bitcoin/bitcoin/issues/5645#issuecomment-69599680

**Comment by CryptoCoderz** [comment] 2018-01-26 08:22
Hello typoworx-de,

Thank you for taking the time to bring this to our concern.
[What you're experiencing can be resolved by utilizing the blockchain snapshot available here](https://espers.io/wallet.php) _as well as ensuring that you are on Espers v0.8.7.2 as that is the only version that is able to synchronize the official blockchain (the newest wallet)_

This is not actually related to the heartbleed as we are utilizing openssl 1.0.2l+ (as of just recently now on openssl 1.0.2n which was just released this past December) Only version of openssl prior to openssl 1.0.1j were susceptible to the attack

You're also experiencing orphans as truant clients attempt to sync with you but don't have the correct chain so your client orphans the attempted sync blocks and offlines the bad connection. This is caused because many users either did not update or update late causing themselves to be forked and giving you a hard time syncing, if you allow your wallet some time and don't just resync it when it hangs up with orphans you'll notice it will in fact continue syncing once it finishes processing through the orphans. It's a superficial error that was caused by flash updating late last year and early this one.

Expect sync to smooth out over the coming weeks as more and more users finally hop onto the correct chain which is the majority of the clients that are connected.

**For smoother syncing also use this nodelist which is updated periodically:** [Click Here](https://espers.io/download/nodes/node-list.txt)

We will now close this issue as it has been addressed. Future releases will further improve sync and connection control to avoid these kinds of hiccups.

**Closed as completed by CryptoCoderz** 2018-01-26 08:22 UTC

**Comment by typoworx-de** [comment] 2018-01-29 13:43
Thanks!
